# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/wikipaddle.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rpc/wikipaddle.proto", :syntax => :proto3) do
    add_message "wikipaddle.api.v1.GetGuidesCollectionRequest" do
      optional :page, :int32, 1
    end
    add_message "wikipaddle.api.v1.GetGuidesCollectionResponse" do
      optional :pagination, :message, 1, "wikipaddle.api.v1.Pagination"
      repeated :guides, :message, 2, "wikipaddle.api.v1.GuideCollectionItem"
    end
    add_message "wikipaddle.api.v1.GuideCollectionItemPhoto" do
      optional :url, :string, 1
    end
    add_message "wikipaddle.api.v1.GuideCollectionItem" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :country, :string, 3
      optional :state, :string, 4
      optional :localizedDistance, :string, 5
      optional :starRating, :string, 6
      repeated :photos, :message, 7, "wikipaddle.api.v1.GuideCollectionItemPhoto"
    end
    add_message "wikipaddle.api.v1.GetCurrentUserRequest" do
    end
    add_message "wikipaddle.api.v1.Pagination" do
      optional :currentPage, :int32, 1
      optional :perPage, :int32, 2
      optional :totalResults, :int32, 3
      optional :totalPages, :int32, 4
    end
    add_message "wikipaddle.api.v1.UserRequest" do
      optional :id, :string, 1
    end
    add_message "wikipaddle.api.v1.User" do
      optional :id, :string, 1
      optional :firstName, :string, 2
      optional :lastName, :string, 3
      optional :fullName, :string, 4
      optional :avatarUrl, :string, 5
    end
    add_message "wikipaddle.api.v1.UserResponse" do
      optional :user, :message, 1, "wikipaddle.api.v1.User"
    end
    add_message "wikipaddle.api.v1.GuideRequest" do
      optional :id, :string, 1
    end
    add_message "wikipaddle.api.v1.GuideResponse" do
      optional :guide, :message, 1, "wikipaddle.api.v1.Guide"
    end
    add_message "wikipaddle.api.v1.LatLng" do
      optional :latitude, :double, 1
      optional :longitude, :double, 2
    end
    add_message "wikipaddle.api.v1.Guide" do
      optional :id, :string, 1
      optional :title, :string, 2
      optional :description, :string, 3
      optional :url, :string, 5
      optional :startLatLng, :message, 6, "wikipaddle.api.v1.LatLng"
      optional :endLatLng, :message, 7, "wikipaddle.api.v1.LatLng"
      optional :polyline, :bytes, 8
      optional :country, :string, 9
      optional :state, :string, 10
      optional :localizedDistance, :string, 11
      optional :commentsCount, :int32, 12
      optional :uploadsCount, :int32, 13
      optional :starRating, :string, 14
    end
    add_message "wikipaddle.api.v1.FitnessActivity" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :startLatLng, :message, 3, "wikipaddle.api.v1.LatLng"
      optional :endLatLng, :message, 4, "wikipaddle.api.v1.LatLng"
      optional :polyline, :bytes, 5
    end
    add_message "wikipaddle.api.v1.GuideComment" do
      optional :id, :string, 1
      optional :body, :string, 2
      optional :userFullName, :string, 3
      optional :userAvatarUrl, :string, 4
      optional :createdAt, :string, 5
      optional :starRating, :int32, 6
    end
    add_message "wikipaddle.api.v1.GetGuideCommentsCollectionRequest" do
      optional :guideId, :string, 1
      optional :page, :int32, 2
    end
    add_message "wikipaddle.api.v1.GetGuideCommentsCollectionResponse" do
      optional :pagination, :message, 1, "wikipaddle.api.v1.Pagination"
      repeated :comments, :message, 2, "wikipaddle.api.v1.GuideComment"
    end
    add_message "wikipaddle.api.v1.CreateGuideCommentRequest" do
      optional :guideId, :string, 1
      optional :body, :string, 2
      optional :starRating, :int32, 3
    end
  end
end

module WikiPaddleApi
  module V1
    GetGuidesCollectionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.GetGuidesCollectionRequest").msgclass
    GetGuidesCollectionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.GetGuidesCollectionResponse").msgclass
    GuideCollectionItemPhoto = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.GuideCollectionItemPhoto").msgclass
    GuideCollectionItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.GuideCollectionItem").msgclass
    GetCurrentUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.GetCurrentUserRequest").msgclass
    Pagination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.Pagination").msgclass
    UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.UserRequest").msgclass
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.User").msgclass
    UserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.UserResponse").msgclass
    GuideRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.GuideRequest").msgclass
    GuideResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.GuideResponse").msgclass
    LatLng = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.LatLng").msgclass
    Guide = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.Guide").msgclass
    FitnessActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.FitnessActivity").msgclass
    GuideComment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.GuideComment").msgclass
    GetGuideCommentsCollectionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.GetGuideCommentsCollectionRequest").msgclass
    GetGuideCommentsCollectionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.GetGuideCommentsCollectionResponse").msgclass
    CreateGuideCommentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wikipaddle.api.v1.CreateGuideCommentRequest").msgclass
  end
end
