name: RubyGem release

on:
  push:
    paths:
      - "rubygem/**"
      - ".github/workflows/rubygem_release.yml"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          git config user.name "WikiPaddle Bot"
          git config user.email "opensource@wikipaddle.com"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ./rubygem
      - run: bundle exec rake release
        working-directory: ./rubygem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
