name: RubyGem release

on:
  push:
    paths:
      - "rubygem/**"
      - ".github/workflows/rubygem_release.yml"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        working-directory: ./rubygem
      - run: rake release
        working-directory: ./rubygem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
